uqbar-project/wollok-ts

test/assertions.ts
test/validator.test.ts

Refactored validator tests to use a custom assertion. Also renamed the variables for the nodes being validated to be more expressive, separated test cases within validations, and added a description for each test.

Validator tests refactor

---

src/parser.ts
test/parser.test.ts

Precedence of ** was wrong on method parser.
This is because in most places where we were generating a parser for a list of operators, the list of operators was sometimes ordered in an unconvenient way (for example, * was before ** on that list).
In order to solve this a new parser was added that receives the operators list as a parameter, and returns a parser that will always try the greediest operators first (it orders them in a way that will have ** before *). Did this instead of just reordering the list of OPERATORS because the pattern ...OPERATORS.map(key) was getting repeated all over the place, but we could have also implemented it by reordering the OPERATORS constant.

Fix precedence of **

---

test/interpreter.test.ts

Inside intepreter tests RETURN tests do not follow the same structure as the others.
I moved it inside the other scope, trying to keep indentation correctly.

Put RETURN tests together with others

---

package.json
src/parser.ts
src/wre/game.ts
src/wre/gameMirror.wlk
src/wre/io.wlk
test/game/events.wtest
test/game/io.wtest
test/wtest.ts

Fix https://github.com/uqbar-project/wollok-ts/issues/64
Fix https://github.com/uqbar-project/wollok-ts/issues/66
También agregué un `errorHandler` al objeto `io` para implementar esto en un futuro: https://github.com/uqbar-project/wollok-ts/issues/69
Agregué unos sanity para el `not` en https://github.com/uqbar-project/wollok-language/pull/81 y ya se banca todos los sanity de lang (master) excepto los de `instanceVariableMirror` que queda para después.

Fix sanities

---

src/wre/game.ts

Los siguientes métodos van a ser deprecados en base a lo acordado en [este issue](https://github.com/uqbar-project/wollok-language/issues/57).
game.addVisualIn(obj,pos)
game.addVisualCharacterIn()
position.drawElement(e)
position.drawCharacter(e)
Para conocer la posición de un visual lo que haremos será enviar el mensaje `position()`.
Related: [PR wollok-run-client](https://github.com/uqbar-project/wollok-run-client/pull/66), [PR wollok-language](https://github.com/uqbar-project/wollok-language/pull/111)

Deprecated methods

---

src/extensions.ts
src/index.ts
src/model.ts
src/validator.ts
src/wre/lang.ts
test/validator.test.ts

- Differentiate expected errors whose level don't match with a different message ✅ 
- Compile and link the files being validated ✅ 
- Adding extension methods for checking list emptyness ✅ 
- Fix for methodNotOnlyCallToSuper ✅

Validator enhancements

---

src/extensions.ts
src/index.ts
src/interpreter/runtimeModel.ts
src/jsonUtils.ts
src/linker.ts
src/model.ts
src/parser.ts
src/validator.ts
src/wre/lang.ts
test/assertions.ts
test/linker.test.ts
test/validator-deprecated.test.ts
test/wtest.ts

Ahí estuve metiendo mano para evitar que entremos en loop al hacer los imports. Uno de los temas que había era que `extensions.ts` importaba List de `model.ts` y a su vez `model.ts` necesitaba cosas de `extensions.ts`.

Fix imports - avoid cyclic loop

---

README.md

Se cambio el link del TSLint deprecado por el nuevo dentro del archivo README.md.

Se cambio el link del TSLint deprecado por el nuevo.

---

.vscode/launch.json
package-lock.json
src/validator.ts
test/validator.test.ts

Fix https://github.com/uqbar-project/wollok-ts/issues/136
Se agregaron estos tests a Language: https://github.com/uqbar-project/wollok-language/pull/154.
Se tocó principalmente cómo se corren los tests de las validaciones:
1. Se agregó un assertion para `sourceMap` (que es importante para el IDE), porque había un bug en el armado de los problemas (se seteaba en `source`).
2. La annotation del Expect se attachea a la asignación y el error es en la variable. No me decidía cómo cambiar esto: 
- Si cambiar el parser para poder attacharlo a la variable, pero ahí iba a tener el mismo problema con la asignación.
- Poder poner paréntesis en lugares raros (como antes del `=` )
- Si tocar el Linker para que el error esté en la asignación, pero me gusta que esté en la variable.
- Así que al final le …

Fix Missing reference error

---

src/wre/lang.ts

Bueno, reavivo la discusión de https://github.com/uqbar-project/wollok-language/issues/140 con un PR cagón.
En un lenguaje de programación industrial, compro que el fullyQualifiedName es definitivamente una mejor decisión a la hora de imprimir por consola un módulo.
Pero:
- en el tamaño que van a tener los proyectos en la facu, no debería ser tan problemático desambiguar alla Smaltalk.
- me preocupa que ver "aves.Golondrina" contribuya a la confusión que hoy tienen de **diferenciar instancia de clase**. 
- no me gustaba como quedaba "a aves.Golondrina", por eso maté el FQN.
- En [la doc de kindName](https://github.com/uqbar-project/wollok-language/blob/master/src/wollok/lang.wlk#L122-L130) decía que devuelve algo de este estilo.
----------------------------------
Sobre la implementación, …

kindName now responds an Object and not FQN

---

src/linker.ts
test/linker.test.ts

Relinkeo de un Environment:  significa hacer un `link` de packages pasando un base-environment. El problema con esto es cuando colisionan los packages: o sea, pasás un nuevo package con el mismo nombre que uno viejo (o que de esa lista que se le pasa haya dos packages con el mismo nombre).
Esa lógica implica un merge de entidades, la idea con esto es que el uso del environment pueda ser **incremental**. Esto está pensado para un IDE en donde las ediciones son dentro de un solo archivo (que se representa como un package!) y solamente tener que pasear ese archivo y poder _integrarlo_ al resto del Environment.
Había un problema en este **relinkeo** que evitaba "borrar" entidades, por ejemplo quiero _renombrar_ la clase de un objeto, la vieja clase nunca se borraba. Esto es porque siempre se …

Fix relink

---

src/model.ts

En el desarrollo del lsp [surgio un filter](https://github.com/uqbar-project/wollok-lsp-ide/pull/43#discussion_r1021393269), tenerlo en el mismo lugar que el `forEach` parecia la opcion mas correcta.

filter node children

---

src/parser.ts
test/parser.test.ts

Closes #139 
Ahora `pepita`:
```wlk
object pepita {
var peso = 0
method come(comida) {
peso = comida.
}
}
```
Se parsearia a:
```js
{
name: 'pepita',
kind: 'Singleton',
members: [
{ name: 'peso', kind: 'Field' },
{ 
name: 'come', 
parameters: [ { name: 'comida', kind: 'Parameter' } ], 
body: {
sentences: [
{ 
kind: 'Assignment', 
variable: { name: 'peso', kind: 'Reference' }, 
value: { kind: 'Reference', name: 'comida' } // dejando afuera el '.'
},
],
problems: [ { code: 'malformedSentence' } ]
}  
}
]
}
```

body should recover from malformed sentence

---

package-lock.json
package.json
src/linker.ts
src/model.ts
src/validator.ts

Se updatea la versión de Wollok, estaba apuntando a una vieja donde faltaban los últimos tests que agregamos a partir de las pruebas con el LSP.
Eso se había roto después de migrar de Typescript, ahí recuperé los cambios. 
También con esta versión detectamos problemas con imports circulares.

Update wollok version

---

src/model.ts
src/parser.ts
src/validator.ts
test/game.test.ts
test/parser.test.ts
test/validator.test.ts

Fix https://github.com/uqbar-project/wollok-lsp-ide/issues/83
Fix #158 
Ahora los metodos de consulta pueden marcar su "body" como una sentencia malformada
Tambien arregla un typo de las validations que fixea #158 
Tests: https://github.com/uqbar-project/wollok-language/pull/161

Expression body parser

---

package.json
src/model.ts
src/parser.ts
src/validator.ts
test/game.test.ts
test/parser.test.ts
test/validator.test.ts

Fix https://github.com/uqbar-project/wollok-lsp-ide/issues/54
- La validación estaba de esa forma para contemplar atributos heredados.
- La dejé solamente para atributos heredados, hice que devolviese `values` con un solo elemento (nombres separados por comas) para que sea traducible (interpolable).
- Agregué otra validación para los Fields de Singletons sin inicializar (o sea, en ese caso, se marca en el atributo en vez de en el objeto).
(Viniendo la screenshot...)

Validations: parser + attribute names

---

package-lock.json
package.json
src/validator.ts

Bueno, esto requiere varias partes: acá viene la parte del validador, para separarlo en otra tipificación.
De paso, creé una función para determinar si una clase hereda de otra custom (que no sea Object).
Para que pase el CI necesitamos mergear primero los tests de wollok-language que voy a crear ahora y van a estar asociados a este PR.

Fix #159 singleton abstract methods

---

src/constants.ts
src/index.ts
src/interpreter/runtimeModel.ts
src/validator.ts
src/wre/lang.ts

La idea es resolver [este issue](https://github.com/uqbar-project/wollok-ts-cli/issues/65) que está cargado para wollok-ts-cli.
Este PR viene de la mano de [este otro PR](https://github.com/uqbar-project/wollok-ts-cli/pull/95), donde acá
- filtro los frames asociados con el fully qualified name (`wollok.`) . Esto es algo que ya se hacía en Wollok Xtext y [que se implementó para wollok-cli que usa Java](https://github.com/uqbar-project/wollok/issues/1660).
- agregué de paso un archivo `constants.ts` donde la idea es poder seguir metiendo cosas ahí.
Me encantaría poder filtrar el stack trace de Typescript (es gracioso que en Wollok Xtext pasaba a veces con [el stack trace de Java](https://github.com/uqbar-project/wollok/issues/1375)), pero la verdad es que es muy raro como WollokException …

Filtering wollok base frames from stack trace & adding constants

---

src/interpreter/runtimeModel.ts

Cierra #180 #35 y #36. Se valida que al momento de instanciar sea una clase y luego se valida que sea abstracta.

Fix #180 #35 #36 should not get an instance

---

src/interpreter/runtimeModel.ts

Eso, extraño el comportamiento de new List(), dejaba como innerValue `undefined` y hacía que todo se rompiera cuando lo querías usar (no funcionaba agregar elementos después). Algo similar pasaba con el new Set. Con este cambio se arregla.

Fix #179 new List() and new Set() fail

---

src/constants.ts
src/interpreter/runtimeModel.ts
src/validator.ts

Arregla #123 
Este PR modifica la validation ya existente `shouldUseOverrideKeyword` para que no aparezca si el metodo es initialize.
El programa que use para testearlo es ([PR en wollok-language](https://github.com/uqbar-project/wollok-language/pull/164)):
```wollok
// This describe should not trigger a shouldUseOverrideKeyword warning
// @Expect(code="shouldUseOverrideKeyword", level="warning")
describe "Fake describe" {
method initialize() {
}
test "2 == 1 + 1" {
assert.equals(2, 1+1)
}
}
class Perro {
// @Expect(code="shouldUseOverrideKeyword", level="warning")
method initialize() {
}
method ladrar() {
return "guau"
}
}
```
Una pregunta que tengo es, hay algun `NotExpect`? ya que en este caso quiero testear que no aparece la validation.

make shouldUseOverrideKeyword ignore initialize method

---

src/constants.ts
src/extensions.ts
src/index.ts
src/model.ts
src/parser.ts
src/validator.ts
test/parser.test.ts
test/typeSystemInference.test.ts
test/utils.ts
test/validator.test.ts

@PalumboN : Acá yo hice una solución (marco solo el nombre, como en Xtext, me gusta más):
pero más allá de que hay que revisar las otras validaciones a ver qué onda (fijate que la otra validación quedó igual) a mí me gustaría tener algo como
```wollok
class SomeClass {
@Expect(code="shouldNotDefineUnusedVariables", level="warning", expectedOn="unusedVariable")
var unusedVariable = 0
```
La macana es que estamos un poco lejos de ésto, porque en el nodo no tenemos nada del texto, solo el archivo, con lo cual para poder hacer el cálculo en base al sourceMap del nodo tenés que hacer un laburo medio paja. La alternativa a eso podría ser
```wollok
class SomeClass {
@Expect(code="shouldNotDefineUnusedVariables", level="warning", range="7:20")
var unusedVariable = 0
```
que es más lograble, hay …

Fix #170 unused variable

---

package-lock.json
src/model.ts
src/parser.ts
src/printer/print.ts
src/printer/utils.ts
test/parser.test.ts
test/printer.test.ts

Soluciona item de #190 
Para poder mostrar el operador correcto (e.g. `not`, `!` o `negate`) lo guarda en el `Send` al parsear.

Formatter for prefix operators

---

package-lock.json
src/model.ts
src/typeSystem/typeVariables.ts

El Type System estaba ignorando las carpetas que comenzaban con `wollok` 😓 
Ahí lo cambié y agregué un método en el Node más peola.

Fix ignore wollok code in Type System

---

package.json
src/linker.ts
src/typeSystem/typeVariables.ts
src/validator.ts

Viene de la mano
- un [PR de Language](https://github.com/uqbar-project/wollok-language/pull/172) para agregar tests y
- y otro de [LSP-IDE](https://github.com/uqbar-project/wollok-lsp-ide/pull/141) para mejorar el mensaje y mostrar cuáles son los métodos:
Resuelve #211

Fix #211 should implement all methods in hierarchy

---

src/validator.ts

Se corrige #167 agregando el test reportado en el issue en [otro PR](https://github.com/uqbar-project/wollok-language/pull/173) de Language. Para eso aprovechamos una definición que considera casos que se estaban escapando en el validador actual.

Fix #167 -> Getter method should return a value

---

src/interpreter/runtimeModel.ts
src/validator.ts

Agrega por un lado un validador para que salte una asignación a un Field que entra en loop infinito:
Y al intérprete se le agrega esa validación para que tire un error más representativo:
Viene acompañado de 2 PRs:
- [LSP IDE](https://github.com/uqbar-project/wollok-lsp-ide/pull/142) para incorporar mensaje de error
- [Language](https://github.com/uqbar-project/wollok-language/pull/174) para incorporar un sanity test

Fix #195 Recursive Assignment

---

src/constants.ts
src/interpreter/runtimeModel.ts
src/model.ts
src/typeSystem/constraintBasedTypeSystem.ts
src/typeSystem/typeVariables.ts
src/validator.ts
src/wre/lang.ts

Ya no se reporta la variable como sin ser usada.
De paso `<apply>` queda como constante...
Relacionado hay un [PR de language](https://github.com/uqbar-project/wollok-language/pull/176)

Fix #193 Unused variable actually used in block

---

src/typeSystem/typeVariables.ts

Cuando el if está vacío en la sentencia then, el type system rompía y eso impedía validar el documento. Ahora sí se puede generar el warning:
Relacionado con 
- [un PR de language](https://github.com/uqbar-project/wollok-language/pull/175) que agrega el test de regresión
- [un PR de LSP-IDE](https://github.com/uqbar-project/wollok-lsp-ide/pull/143) que corrige otro manejo de nulls para hover y mejora el logger

Fix #198 - empty if

---

src/helpers.ts
test/helpers.test.ts
test/interpreter.test.ts

Como parte de la épica de mejoras de UX para LSP-IDE aparecieron varias funciones que están en el archivo wollok.ts y otras en references, mi idea es que desaparezcan y que directamente usemos las definiciones de acá.
[Issue original](https://github.com/uqbar-project/wollok-lsp-ide/issues/147)
Además agregué tests unitarios

Moving functions from lsp-ide into wollok-ts

---

src/helpers.ts

#124 
- actualmente no tomaba en cuenta métodos de un describe
- tampoco cuando inicializabas lists o sets en base a otras definiciones
- [Language](https://github.com/uqbar-project/wollok-language/pull/179), agregamos clases de equivalencia para set, list y el método initialize de un describe, además de probar el caso donde tiene que detectar una variable sin usar en un wtest

Fix #124 unused variable actually used in describe method

---

package-lock.json
package.json
src/linker.ts
src/model.ts
src/parser.ts
src/validator/index.ts
src/validator/values.ts
test/linker.test.ts
test/utils.ts
test/validator.test.ts

Fix https://github.com/uqbar-project/wollok-ts/issues/236
Maybe https://github.com/uqbar-project/wollok-ts/issues/207
Gran parte de https://github.com/uqbar-project/wollok-ts/issues/166 (faltan algunos detalles, podemos abrir otros issues para seguirla...)
Lo que hice fue:
- Al linkear los imports, si colisionan las referencias, los `.wlk` ganan sobre los `.wtest`. Sino deja el primero que encuentra (esto es para evitar que definiciones locales se pisen con globales).
- Agregué una validación para no tener `.` en los nombres de archivos (que rompen los fqn).
- Para testear, tuve que tocar el parser para que no rompan archivos con solo metadata (comentarios o annotations)

Fix import with collision

---

package-lock.json
package.json
scripts/validateWollokVersion.ts
src/wre/game.ts
test/game.test.ts

Tests para este PR: https://github.com/uqbar-project/wollok-language/pull/183
Moví el error reporter como una property en Language, ya que la lógica estaba allá (además confío que no afecta en la performance).
Además aproveché para sacar tests que ya se movieron como sanity 🧹

Tests for errors on game events

---

src/wre/game.ts

este PR es para intentar mejorar el tiempo de respuesta de los eventos de colisión (https://github.com/uqbar-project/wollok-ts-cli/issues/157)
El cambio consiste en reemplazar, cuando se pueda, la llamada a `yield* this.send('position', visual)` por un `visual.get('position')` en el método `getObjectsIn()` que es llamado por los eventos onCollide y whenCollide
Se notó una diferencia importante de velocidad entre el primer método y el segundo. En el entorno de pruebas, con unos cientos de visuales, cada llamada a `getObjectsIn()` pasó de unos 30ms a 0.5ms entre un método y otro
El problema es que el primer método sólo se puede utilizar para visuales que tengan `position` definido como `property`, por lo que se hace un chequeo preguntando si el método `position()` es sintético, si es así, …

Refactorización de onCollide

---

package-lock.json
src/extensions.ts
src/parser.ts
test/parser.test.ts

En Windows los source maps se estaban formando mal, esto es porque en los sistemas operativos ~~de bien~~ basados en Unix el caracter de new line es el `\n` pero en Windows son **dos** caracters `\r\n`
Ahora el/los caracter/es a utilizar son calculados y el calculo para sanitizar los sourcemaps se basan es esto.

Sanitize whitespace by os

---

package-lock.json
src/helpers.ts
src/linker.ts
src/model.ts
src/validator/index.ts

Fix https://github.com/uqbar-project/wollok-ts/issues/257
Fix https://github.com/uqbar-project/wollok-ts/issues/253
Como no llegamos a consenso sobre las extensiones de archivos, decidí dejar los importas al igual que funcionaban en Xtext:
- Solamente se pueden importar archivos `.wlk`
- No valida archivos con el mismo nombre (pero distinta extensión).
- Así que por ahora ese issue queda pendiente
------
Después de estos cambios, este ejercicio de **superpoderoses** (que me _encanta_!) funca piola de una:
https://github.com/obj1unq/2021s1-simulacro-superpoderoses-lgassman

Imports xtext

---

src/printer/print.ts
test/printer.test.ts

Fix #278 
Empty object with comments now are correctly formatted.
Before:
```wollok
object pepita {  
// un comentario
}
```
Was formatted to 
```wollok
object pepita {
}
```
Now keeps the comment.

Printer :: Empty object with comments

---

src/interpreter/runtimeModel.ts

Fix https://github.com/uqbar-project/wollok-ts/issues/276
El problema era que solo se estaban cacheando los enteros.
Lo cambiamos para que cachee todos los números que se interpretan... espero que no tenga daños colaterales :P

Cache float numbers too

---

src/interpreter/runtimeModel.ts

Mergear antes https://github.com/uqbar-project/wollok-language/pull/217

Fix #297 - Cyclic const instance references

---

package.json
src/linker.ts
test/interpreter.test.ts
test/linker.test.ts

Sobre el problema reportado en https://github.com/uqbar-project/wollok-ts/issues/308, me tomó mucho laburo tratar de reproducirlo, pero acá dejo dos tests:
- el del linker que pasa irremediablemente
- el del interpreter, que rompe cuando vos tenés una jerarquía, cuando vos hacés
```wollok
// en un package
import B.*
class A inherits B {}
// en otro package
import C.*
class B inherits C {}
// y en otro package
class C {
method bla()
}
```
no funciona `new B().bla()` (dice que no lo entiende). Si en cambio hacés:
```wollok
// en un package
import B.*
class A{}
// en otro package
import C.*
class B inherits C {}
// y en otro package
class C {
method bla()
}
```
funciona perfectamente.
@ivojawer @PalumboN , me gustaría verlo en nuestras sesiones de los martes.

Error en imports que se hacen desde diferentes packages (el orden causa error)

---

src/validator/index.ts

No mucho más para agregar, faltaba chequear que el método fuera synthetic (lo que significa que se generó, en este caso por ser una property).

Fix de shouldUseOverrideKeyword para una property

---

.github/workflows/node.js.yml
scripts/fetchLanguage.ts

En esta PoC la idea es ver si volvemos a usar https en lugar de ssh, que en algún momento empezó a generar conflictos, para no necesitar en github actions configurar una clave privada, si nos queremos bajar language que es un repo público.

Resolver el problema del CI para forks

---

src/helpers.ts
test/interpreter.test.ts

El closure se define como un Method, eso causa que cuando estás en el contexto de un super si buscás el primer método de los ancestors te traiga el mismo closure y quiera ejecutar `<apply>` dentro del objeto receptor. Como `<apply>` es un pseudo método interno, filtramos los métodos construidos de esta manera y super funciona de la manera esperada.
Tiene su correspondiente sanity test: https://github.com/uqbar-project/wollok-language/pull/224

Fix #304 Super inside closure

---

package.json
src/interpreter/interpreter.ts
src/interpreter/runtimeModel.ts
test/game.test.ts
test/interpreter.test.ts

Dejo un WIP para poder pelotearlo en alguna juntada de los martes. Ver más detalle en #302

Stack trace ante un error no reconoce el body de un método o test

---

package-lock.json
src/validator/index.ts

Avoid redefine identity

---

src/validator/index.ts

fix super incorrecto

---

package-lock.json
src/interpreter/runtimeModel.ts
test/interpreter.test.ts

fix [#11](https://github.com/uqbar-project/wollok-ts-cli/issues/110)

correccion de error en repl cuando se redefinia una variable

---

package.json
src/parser.ts
test/parser.test.ts
test/printer.test.ts

Se arreglan los comentarios después de envío de mensajes.
Eso hizo saltar la ficha de que la función `sanitizeWhitespaces` tenía un par de casos borders que faltaban. 
Lo arreglamos pero @fdodino sugería tener un función que calcule la line y la column a partir del offset: `coordinates(input, offset) -> { from, to }` 
Esto arregla el issue de nuestro querido amigo @isaiaslafon 
Fix https://github.com/uqbar-project/website-wollok-ts/issues/53

Fix parser multiline comment

---

src/wre/lang.ts

Ver https://github.com/uqbar-project/wollok-ts-cli/pull/209

Nueva nativa io.serve()

---

.vscode/launch.json
package-lock.json
package.json
src/index.ts
src/interpreter/interpreter.ts
src/parser.ts
src/wre/natives.ts
test/assertions.ts
test/game.test.ts
test/interpreter.test.ts
test/natives.test.ts
test/parser.test.ts
test/utils.ts
test/wtest.ts
tsconfig.json

Permite construir un Intérprete que reciba funciones nativas escritas por el usuario
El principal cambio es que en lugar de importar las natives de WRE, se debe importar la función natives(), la cual se invoca  conas las natives de usuario  (o vacío si no hay) y devuelve un merge de éstas con las nativas del WRE.
Agrega un deepEquals en los assertions para verificar que el merge   se produzca como corresponde

User natives

---

.vscode/settings.json
src/validator/index.ts

fix: should match superclass not working with if else

---

.gitignore
src/wre/lang.ts

- **roundDown()** and **roundUp()** son equivalentes a **floor()** and **ceil()**
Así que se pusieron como sugar. Se agregaron en **truncate(_decimals_)**, **roundDown(_decimals_)**, **roundUp(_decimals_)** excepciones al no se entero _decimals-. 
- Se agregaron de todo los **tests** correspondientes. 
Relacionado con el **PR** y **Branch** de language:
- https://github.com/uqbar-project/wollok-language/pull/243
- https://github.com/uqbar-project/wollok-language/tree/fIx-%2386-%23212-floor-negative-numbers-and-ceiling

Fix #86 #212 floor for negative numbers and ceiling

---

src/interpreter/interpreter.ts
src/interpreter/runtimeModel.ts
src/linker.ts
src/parser.ts
test/helpers.test.ts
test/interpreter.test.ts
test/linker.test.ts

- #351 Nos permite tener múltiples líneas en el REPL separadas por `;` (el `Enter` igual hace que dispares la evaluación de la expresión). La última expresión es lo que te devuelve al REPL.
- #350 Se pueden definir entidades como clases, objects, mixins. También acepta imports en la multiline sentence

Add object, class & mixin to REPL
