- test/parser.test.ts
**Added:**
- Tests of comments, names, local references, fully qualified references, files, imports, programs, tests, packages, classes, mixins, singletons, fields, methods, constructors, variables, returns, assignments, infix and prefix operations, sends, constructors, super calls, if, try and throw expressions
**Parsing failed at tests of:** 
- Comments
- Classes
- Methods
- Constructors
- Assignments
- Prefix operations
- Sends
- Try expressions
**Errors I couldn't solve / I don't understand why they happen:**
_Names_
should parse names that begin with _:
```
AssertionError: expected '_foo123' to have nested property 'source.start.offset'
at Proxy.<anonymous> (test\assertions.ts:50:23)
at Proxy.methodWrapper (node_modules\chai\lib\chai\utils\addMethod.js:57:25)
at Context.it …
```
> Rest of the tests added 

- test/parser.test.ts
Node tests added for all previous tests
> Node tests added

- src/validator.ts
- test/validator.test.ts
I added some checks to detect:
// Name capitalization
// Only one (the last) parameter can be vararg
I need to refactor the way I return problems and make a builder for them
> Some validator's functionalities added

- src/validator.ts
- test/validator.test.ts
Changes:
- singletonIsNotUnnamed receives a singleton
- Fix hasCatchOrAlways
- Tests enhancement
New validations: 
- nonAsignationOfFullyQualifiedReferences
- nameIsCamelCase (some references must be camel case, but how can I differentiate references to superclasses or mixines from other references?)
- fieldNameDifferentFromTheMethods
> Changes and new validations

- src/validator.ts
Hi!
Grepped the project for TODOs, found this kinda low hanging.
It's kinda WIP because I'd like to find a way to sugar it a bit more (calling it like Self isNotPresentIn 'Program'), but I think it is not possible in js :(
> isNotPresentIn in validator

- package-lock.json
- package.json
- src/behavior.ts
- src/builders.ts
- src/filler.ts
- src/interpreter.ts
- src/log.ts
- src/model.ts
- src/wre/game.ts
- src/wre/lang.ts
- src/wre/lang.wlk
- test/interpreter.test.ts
- test/sanity.ts
Evaluation no has contexts instead of saving all locals on frames
> Alt contexts

- src/index.ts
@nscarcella : nunca me llegó el mail ni la notificación del PR anterior, pero ya que era un toque solo, volví a generar un nuevo PR esta vez con el historial más limpito y todo joya para que lo mires.
> adding environment as an optional parameter for building a new one

- package-lock.json
- src/builders.ts
- src/interpreter.ts
- src/log.ts
- test/interpreter.test.ts
- test/wtest.ts
`Evaluation` properties `instances` and `frameStack` are publicly accessible (and effectively accessed) from outside. This prevents from having a separate implementation of the Evaluation using different schemas for instantiation or stacks.
> Encapsulate properties of Evaluation class

- README.md
Cosas que tenía en el repo hace mil.
> small README addings

- package.json
Adding capability of running tests faster.
Also added script for validation tests.
> Faster tests

- src/validator.ts
- test/validator.test.ts
- Add wpgm file extension to validator sync
- A minor fix to show error codes for file errors
> Validator enhancements

- src/extensions.ts
- src/interpreter/runtimeModel.ts
- src/model.ts
- src/validator.ts
- test/model.test.ts
- test/validator.test.ts
Siguiendo con la saga [de validaciones](https://docs.google.com/spreadsheets/d/1OPqJEXTufnpD_H2Awenocv8XQbsTqpWVJX8VHv2KPkY/edit#gid=0), sacamos del horno la segunda entrega. Quedan pendientes 30 validadores y el refactor de uno de los que aparecen acá.
> Validators second phase

- package-lock.json
- src/wre/io.wlk
- test/game/events.wtest
https://github.com/uqbar-project/wollok-language/pull/135
Se testeó la correcta funcionalidad de los métodos de la clase Tick (start, stop, isRunning, interval), además de la propiedad inmediate. También se testeó el método createTick del objeto game, y el hecho de que los tick events con ejecuciones por algún motivo pendientes, se resuelvan en cuanto se pueda ejecutando el bloque la cantidad de veces correspondientes al tiempo transcurrido según el intervalo.
> Tests for Tick class methods and game.createTick method

- src/wre/lang.ts
> Fix message in generateDoesNotUnderstandMessage

- src/wre/gameMirror.wlk
- test/game/events.wtest
Fixes #132 
Se movio el código a https://github.com/uqbar-project/wollok-language/pull/143
> Movemos addVisualCharacter y sus test a Language

- src/linker.ts
- src/validator.ts
- test/linker.test.ts
- test/validator.test.ts
Arreglo algunos problemas con las validaciones [reportados en el discord de Uqbar](https://discord.com/channels/737094307902914570/737097628193390633/1070472287410729001)
Tests in: https://github.com/uqbar-project/wollok-language/pull/155
> Fix validations

- package.json
- src/linker.ts
- src/validator.ts
- test/game.test.ts
- test/linker.test.ts
Fix https://github.com/uqbar-project/wollok-ts/issues/96
El problema parecía ser que las referencias globales estaban pisando la contribución del package a su padre (Environment).
Al evitar eso se arregló (??. Las pruebas con vscode funcionaron mejor 👍 
Agregué un test que rompía y ya no y también en lang.
También estuve tocando cosas del validador con las que me fui topando. También tests sobre eso en lang.
> Linking globals not override defined packages

- src/validator.ts
Agregué esta validación para programs y constants globales
> Duplicated entities error for all

- .github/workflows/node.js.yml
- package.json
Eso, ejecutamos el build en el ci.
De paso le subí la versión en el package.json.
> Fix #186 run build in ci

- CHANGELOG.md
- package.json
Este PR deja prolija la nueva versión de Wollok TS para usar a la 4.0.9
Validado con mi gran amigo @ivojawer !
> Updating CHANGELOG & using new version

- src/interpreter/runtimeModel.ts
- src/validator.ts
Resuelve #209 con ayuda de [este PR](https://github.com/uqbar-project/wollok-language/pull/171) de Wollok Language donde están los tests. También arreglé el mensaje que muestra el IDE (estaba repetido con otro y era confuso).
> Fix #209 instantiate object with null references

- src/printer/print.ts
- test/printer.test.ts
> Only test printer

- package.json
- src/interpreter/runtimeModel.ts
- src/wre/lang.ts
- test/interpreter.test.ts
Ver [las conclusiones del issue original](https://github.com/uqbar-project/wollok-ts/issues/231#issuecomment-2027119932) para más información.
> Fix #231 uninitialized attributes for wko

- src/extensions.ts
- src/typeSystem/typeVariables.ts
Fix https://github.com/uqbar-project/wollok-ts/issues/149
Es medio una gilada, pero era algo que tenía pendiente de la otra vez :P
Tuve que usar un `'OTHERWISE' as const` que no quería, pero blah
> Hi othewise matcher

- .editorconfig
- README.md
- scripts/fetchLanguage.ts
- src/wre/game.ts
Cambios:
* se agrega configuración para EditorConfig
* se reemplaza método de obtención de wollok language de `ssh` por `http`
* se modifica `getObjectsIn` para lograr mejora en la velocidad de procesamiento de los colliders, como parte del conjunto de soluciones para el issue https://github.com/uqbar-project/wollok-ts-cli/issues/143
* nota: con este cambio, en mi entorno el tiempo que toma en ejecutar este método bajó de aprox 500ms a unos 30ms, para cerca de 300 visuales
> Fix: problemas de performance en onCollide

- .github/workflows/node.js.yml
- README.md
- src/extensions.ts
- src/helpers.ts
- src/interpreter/interpreter.ts
- src/interpreter/runtimeModel.ts
- src/model.ts
- src/printer/print.ts
- src/typeSystem/typeVariables.ts
- src/validator/index.ts
- src/validator/sourceMaps.ts
- test/extensions.test.ts
- test/helpers.test.ts
- test/model.test.ts
- #156 
- De paso, cambié el CI a codecov que si bien no es tan cheto como coveralls al menos funciona (coveralls viene teniendo problemas serios para mostrar el reporte de las líneas cubiertas)
- Rebaseé de main y le puse la función otherwise
- También traté de unificar funciones que habían quedado duplicadas o muy similares
> Migrate common definitions from LSP and Mobile into TS

- package-lock.json
- src/extensions.ts
- src/parser.ts
- src/printer/print.ts
- test/assertions.ts
- test/parser.test.ts
- test/printer.test.ts
Fix #207
Fix #202
Varias cosas del #200 
Fix #199 
Fix #173 
Fix #108 
Aproveché que me metí con esto y arreglé varios problemas del parser, sobre todo el manejo de los espacios en blanco y comentarios.
_Para más info mirar los issues._
> Fix parser

- src/interpreter/dynamicDiagram.ts
- src/linker.ts
- src/model.ts
- test/dynamicDiagram.test.ts
- test/model.test.ts
Arreglamos el problema que tenía el REPL con los objetos importados desde un archivo + referencias por var/const.
> Refactor Dynamic Diagram

- src/interpreter/runtimeModel.ts
> Current node for frames

- package-lock.json
- package.json
- src/helpers.ts
- src/index.ts
- src/interpreter/runtimeModel.ts
- src/validator/index.ts
- src/validator/messageReporter.ts
- src/validator/problemReporter.ts
- test/helpers.test.ts
- test/messageReporter.test.ts
Resuelve
- https://github.com/uqbar-project/wollok-lsp-ide/issues/177
- https://github.com/uqbar-project/wollok-language/issues/139
- https://github.com/uqbar-project/wollok-lsp-ide/issues/162
- https://github.com/uqbar-project/wollok-lsp-ide/issues/93
Ahora se rompe el CI porque me dio miedo seguir apuntando a la branch de language pero si se fijan el historial los builds pasaban ok, solo que codecov es muy celoso y por más que tuviera 100% de cobertura del reporter me bajaba el total general.
Depende de https://github.com/uqbar-project/wollok-language/pull/205
> Migrate validation messages

- codecov.yml
- test/model.test.ts
El objetivo de este PR es que dejen de fallar otros PRs si bajamos el coverage hasta un 2% (hay veces en los que te baja un 0,05% y te pone la cruz y es molesto). Que baje más de un 2% no bloquea el PR, solo hace fallar ese check y está en nosotros ignorarlo y mergear igual.
En este PR comenté los tests de Method en model.test.ts y pese a que bajó 0,04% me dejó pasar el PR:
Pueden hacer click sobre el check que está al lado del commit aea0066 para volverlo a ver ao vivo.
> Add codecov yml - fix #322

- src/helpers.ts
- src/validator/index.ts
Arregla varios issues de la validación shouldReturnAValueOnAllFlows
- #121 
- #314  
- #265 
El error del CI es porque necesitamos mergear primero language: https://github.com/uqbar-project/wollok-language/pull/247
> shouldReturnAValueOnAllFlows - fixes

- package-lock.json
- src/wre/game.ts
After run all tests 2 test fail:
Also deprecate ground, title and cellSize and moved to language.
> fix #336 Deprecated width and height natives to be implemented in language
